// Pokemon Champions Regulation M-B legal pool.
// Source: metavgc.com / pokemon-home.com (Reg M-B, June 17 2026 – Sep 2 2026).
//
// `slug` is the PokéAPI identifier used to fetch sprites/types.
// Megas are stored separately in REG_MB_MEGAS — sprites still render from
// the base species per the "show base forms" UI rule.

export type FormVariant = { name: string; slug: string };

export type PokemonSpecies = {
  name: string;
  slug: string;
  forms?: FormVariant[];
};

export type MegaEntry = { name: string; baseSlug: string };

export const REG_MB_POOL: PokemonSpecies[] = [
  { name: "Abomasnow", slug: "abomasnow" },
  { name: "Absol", slug: "absol" },
  {
    name: "Aegislash",
    slug: "aegislash",
    forms: [
      { name: "Aegislash (Shield)", slug: "aegislash-shield" },
      { name: "Aegislash (Blade)", slug: "aegislash-blade" },
    ],
  },
  { name: "Aerodactyl", slug: "aerodactyl" },
  { name: "Aggron", slug: "aggron" },
  { name: "Alakazam", slug: "alakazam" },
  { name: "Alcremie", slug: "alcremie" },
  { name: "Altaria", slug: "altaria" },
  { name: "Ampharos", slug: "ampharos" },
  { name: "Annihilape", slug: "annihilape" },
  { name: "Appletun", slug: "appletun" },
  { name: "Araquanid", slug: "araquanid" },
  { name: "Arbok", slug: "arbok" },
  { name: "Arcanine", slug: "arcanine" },
  { name: "Archaludon", slug: "archaludon" },
  { name: "Ariados", slug: "ariados" },
  { name: "Armarouge", slug: "armarouge" },
  { name: "Aromatisse", slug: "aromatisse" },
  { name: "Audino", slug: "audino" },
  { name: "Aurorus", slug: "aurorus" },
  { name: "Avalugg", slug: "avalugg" },
  { name: "Azumarill", slug: "azumarill" },
  { name: "Banette", slug: "banette" },
  { name: "Barbaracle", slug: "barbaracle" },
  {
    name: "Basculegion",
    slug: "basculegion",
    forms: [
      { name: "Basculegion (Male)", slug: "basculegion-male" },
      { name: "Basculegion (Female)", slug: "basculegion-female" },
    ],
  },
  { name: "Bastiodon", slug: "bastiodon" },
  { name: "Beartic", slug: "beartic" },
  { name: "Beedrill", slug: "beedrill" },
  { name: "Bellibolt", slug: "bellibolt" },
  { name: "Blastoise", slug: "blastoise" },
  { name: "Blaziken", slug: "blaziken" },
  { name: "Camerupt", slug: "camerupt" },
  { name: "Castform", slug: "castform" },
  { name: "Ceruledge", slug: "ceruledge" },
  { name: "Chandelure", slug: "chandelure" },
  { name: "Charizard", slug: "charizard" },
  { name: "Chesnaught", slug: "chesnaught" },
  { name: "Chimecho", slug: "chimecho" },
  { name: "Clawitzer", slug: "clawitzer" },
  { name: "Clefable", slug: "clefable" },
  { name: "Cofagrigus", slug: "cofagrigus" },
  { name: "Conkeldurr", slug: "conkeldurr" },
  { name: "Corviknight", slug: "corviknight" },
  { name: "Crabominable", slug: "crabominable" },
  { name: "Decidueye", slug: "decidueye" },
  { name: "Dedenne", slug: "dedenne" },
  { name: "Delphox", slug: "delphox" },
  { name: "Diggersby", slug: "diggersby" },
  { name: "Ditto", slug: "ditto" },
  { name: "Dragalge", slug: "dragalge" },
  { name: "Dragapult", slug: "dragapult" },
  { name: "Dragonite", slug: "dragonite" },
  { name: "Drampa", slug: "drampa" },
  { name: "Eelektross", slug: "eelektross" },
  { name: "Emboar", slug: "emboar" },
  { name: "Emolga", slug: "emolga" },
  { name: "Empoleon", slug: "empoleon" },
  { name: "Espathra", slug: "espathra" },
  { name: "Espeon", slug: "espeon" },
  { name: "Excadrill", slug: "excadrill" },
  { name: "Falinks", slug: "falinks" },
  { name: "Farigiraf", slug: "farigiraf" },
  { name: "Feraligatr", slug: "feraligatr" },
  { name: "Flapple", slug: "flapple" },
  { name: "Flareon", slug: "flareon" },
  { name: "Floette", slug: "floette" },
  { name: "Florges", slug: "florges" },
  { name: "Forretress", slug: "forretress" },
  { name: "Froslass", slug: "froslass" },
  { name: "Furfrou", slug: "furfrou" },
  { name: "Gallade", slug: "gallade" },
  { name: "Garbodor", slug: "garbodor" },
  { name: "Garchomp", slug: "garchomp" },
  { name: "Gardevoir", slug: "gardevoir" },
  { name: "Garganacl", slug: "garganacl" },
  { name: "Gengar", slug: "gengar" },
  { name: "Gholdengo", slug: "gholdengo" },
  { name: "Glaceon", slug: "glaceon" },
  { name: "Glalie", slug: "glalie" },
  { name: "Glimmora", slug: "glimmora" },
  { name: "Gliscor", slug: "gliscor" },
  { name: "Golurk", slug: "golurk" },
  { name: "Goodra", slug: "goodra" },
  { name: "Gourgeist", slug: "gourgeist" },
  { name: "Greninja", slug: "greninja" },
  { name: "Grimmsnarl", slug: "grimmsnarl" },
  { name: "Gyarados", slug: "gyarados" },
  { name: "Hatterene", slug: "hatterene" },
  { name: "Hawlucha", slug: "hawlucha" },
  { name: "Heliolisk", slug: "heliolisk" },
  { name: "Heracross", slug: "heracross" },
  { name: "Hippowdon", slug: "hippowdon" },
  { name: "Houndoom", slug: "houndoom" },
  { name: "Houndstone", slug: "houndstone" },
  { name: "Hydrapple", slug: "hydrapple" },
  { name: "Hydreigon", slug: "hydreigon" },
  { name: "Incineroar", slug: "incineroar" },
  { name: "Infernape", slug: "infernape" },
  { name: "Jolteon", slug: "jolteon" },
  { name: "Kangaskhan", slug: "kangaskhan" },
  { name: "Kingambit", slug: "kingambit" },
  { name: "Kleavor", slug: "kleavor" },
  { name: "Klefki", slug: "klefki" },
  { name: "Kommo-o", slug: "kommo-o" },
  { name: "Krookodile", slug: "krookodile" },
  { name: "Leafeon", slug: "leafeon" },
  { name: "Liepard", slug: "liepard" },
  { name: "Lopunny", slug: "lopunny" },
  { name: "Lucario", slug: "lucario" },
  { name: "Luxray", slug: "luxray" },
  {
    name: "Lycanroc",
    slug: "lycanroc",
    forms: [
      { name: "Lycanroc (Midday)", slug: "lycanroc-midday" },
      { name: "Lycanroc (Midnight)", slug: "lycanroc-midnight" },
      { name: "Lycanroc (Dusk)", slug: "lycanroc-dusk" },
    ],
  },
  { name: "Machamp", slug: "machamp" },
  { name: "Malamar", slug: "malamar" },
  { name: "Mamoswine", slug: "mamoswine" },
  { name: "Manectric", slug: "manectric" },
  {
    name: "Maushold",
    slug: "maushold",
    forms: [
      { name: "Maushold (Family of Four)", slug: "maushold-family-of-four" },
      { name: "Maushold (Family of Three)", slug: "maushold-family-of-three" },
    ],
  },
  { name: "Mawile", slug: "mawile" },
  { name: "Medicham", slug: "medicham" },
  { name: "Meganium", slug: "meganium" },
  { name: "Meowscarada", slug: "meowscarada" },
  {
    name: "Meowstic",
    slug: "meowstic",
    forms: [
      { name: "Meowstic (Male)", slug: "meowstic-male" },
      { name: "Meowstic (Female)", slug: "meowstic-female" },
    ],
  },
  { name: "Metagross", slug: "metagross" },
  { name: "Milotic", slug: "milotic" },
  { name: "Mimikyu", slug: "mimikyu" },
  {
    name: "Morpeko",
    slug: "morpeko",
    forms: [
      { name: "Morpeko (Full Belly)", slug: "morpeko-full-belly" },
      { name: "Morpeko (Hangry)", slug: "morpeko-hangry" },
    ],
  },
  { name: "Mr. Rime", slug: "mr-rime" },
  { name: "Mudsdale", slug: "mudsdale" },
  { name: "Musharna", slug: "musharna" },
  {
    name: "Ninetales",
    slug: "ninetales",
    forms: [
      { name: "Ninetales (Kantonian)", slug: "ninetales" },
      { name: "Ninetales (Alolan)", slug: "ninetales-alola" },
    ],
  },
  { name: "Noivern", slug: "noivern" },
  { name: "Oranguru", slug: "oranguru" },
  { name: "Orthworm", slug: "orthworm" },
  { name: "Overqwil", slug: "overqwil" },
  {
    name: "Palafin",
    slug: "palafin",
    forms: [
      { name: "Palafin (Zero)", slug: "palafin-zero" },
      { name: "Palafin (Hero)", slug: "palafin-hero" },
    ],
  },
  { name: "Pangoro", slug: "pangoro" },
  { name: "Passimian", slug: "passimian" },
  { name: "Patrat", slug: "patrat" },
  { name: "Pelipper", slug: "pelipper" },
  { name: "Pidgeot", slug: "pidgeot" },
  { name: "Pikachu", slug: "pikachu" },
  { name: "Pinsir", slug: "pinsir" },
  { name: "Politoed", slug: "politoed" },
  { name: "Polteageist", slug: "polteageist" },
  { name: "Primarina", slug: "primarina" },
  { name: "Pyroar", slug: "pyroar" },
  { name: "Quaquaval", slug: "quaquaval" },
  { name: "Qwilfish", slug: "qwilfish" },
  { name: "Raichu", slug: "raichu" },
  { name: "Rampardos", slug: "rampardos" },
  { name: "Reuniclus", slug: "reuniclus" },
  { name: "Rhyperior", slug: "rhyperior" },
  { name: "Roserade", slug: "roserade" },
  {
    name: "Rotom",
    slug: "rotom",
    forms: [
      { name: "Rotom", slug: "rotom" },
      { name: "Rotom (Heat)", slug: "rotom-heat" },
      { name: "Rotom (Wash)", slug: "rotom-wash" },
      { name: "Rotom (Frost)", slug: "rotom-frost" },
      { name: "Rotom (Fan)", slug: "rotom-fan" },
      { name: "Rotom (Mow)", slug: "rotom-mow" },
    ],
  },
  { name: "Runerigus", slug: "runerigus" },
  { name: "Sableye", slug: "sableye" },
  { name: "Salazzle", slug: "salazzle" },
  { name: "Samurott", slug: "samurott" },
  { name: "Sandaconda", slug: "sandaconda" },
  { name: "Sceptile", slug: "sceptile" },
  { name: "Scizor", slug: "scizor" },
  { name: "Scolipede", slug: "scolipede" },
  { name: "Scovillain", slug: "scovillain" },
  { name: "Scrafty", slug: "scrafty" },
  { name: "Serperior", slug: "serperior" },
  { name: "Sharpedo", slug: "sharpedo" },
  { name: "Simipour", slug: "simipour" },
  { name: "Simisage", slug: "simisage" },
  { name: "Simisear", slug: "simisear" },
  { name: "Sinistcha", slug: "sinistcha" },
  { name: "Skarmory", slug: "skarmory" },
  { name: "Skeledirge", slug: "skeledirge" },
  { name: "Slowbro", slug: "slowbro" },
  { name: "Slowking", slug: "slowking" },
  { name: "Slurpuff", slug: "slurpuff" },
  { name: "Sneasler", slug: "sneasler" },
  { name: "Snorlax", slug: "snorlax" },
  { name: "Spiritomb", slug: "spiritomb" },
  { name: "Staraptor", slug: "staraptor" },
  { name: "Starmie", slug: "starmie" },
  { name: "Steelix", slug: "steelix" },
  { name: "Stunfisk", slug: "stunfisk" },
  { name: "Swampert", slug: "swampert" },
  { name: "Sylveon", slug: "sylveon" },
  { name: "Talonflame", slug: "talonflame" },
  {
    name: "Tauros",
    slug: "tauros",
    forms: [
      { name: "Tauros (Combat Paldean)", slug: "tauros-paldea-combat-breed" },
      { name: "Tauros (Blaze Paldean)", slug: "tauros-paldea-blaze-breed" },
      { name: "Tauros (Aqua Paldean)", slug: "tauros-paldea-aqua-breed" },
    ],
  },
  { name: "Tinkaton", slug: "tinkaton" },
  { name: "Torkoal", slug: "torkoal" },
  { name: "Torterra", slug: "torterra" },
  { name: "Toucannon", slug: "toucannon" },
  { name: "Toxapex", slug: "toxapex" },
  { name: "Toxicroak", slug: "toxicroak" },
  { name: "Trevenant", slug: "trevenant" },
  { name: "Tsareena", slug: "tsareena" },
  { name: "Typhlosion", slug: "typhlosion" },
  { name: "Tyranitar", slug: "tyranitar" },
  { name: "Tyrantrum", slug: "tyrantrum" },
  { name: "Umbreon", slug: "umbreon" },
  { name: "Vanilluxe", slug: "vanilluxe" },
  { name: "Vaporeon", slug: "vaporeon" },
  { name: "Venusaur", slug: "venusaur" },
  { name: "Victreebel", slug: "victreebel" },
  { name: "Vileplume", slug: "vileplume" },
  { name: "Vivillon", slug: "vivillon" },
  { name: "Volcarona", slug: "volcarona" },
  { name: "Weavile", slug: "weavile" },
  { name: "Whimsicott", slug: "whimsicott" },
  { name: "Wyrdeer", slug: "wyrdeer" },
  { name: "Zoroark", slug: "zoroark" },
];

export const REG_MB_MEGAS: MegaEntry[] = [
  { name: "Mega Barbaracle", baseSlug: "barbaracle" },
  { name: "Mega Blaziken", baseSlug: "blaziken" },
  { name: "Mega Dragalge", baseSlug: "dragalge" },
  { name: "Mega Eelektross", baseSlug: "eelektross" },
  { name: "Mega Falinks", baseSlug: "falinks" },
  { name: "Mega Malamar", baseSlug: "malamar" },
  { name: "Mega Mawile", baseSlug: "mawile" },
  { name: "Mega Metagross", baseSlug: "metagross" },
  { name: "Mega Pyroar", baseSlug: "pyroar" },
  { name: "Mega Raichu X", baseSlug: "raichu" },
  { name: "Mega Raichu Y", baseSlug: "raichu" },
  { name: "Mega Sceptile", baseSlug: "sceptile" },
  { name: "Mega Scolipede", baseSlug: "scolipede" },
  { name: "Mega Scrafty", baseSlug: "scrafty" },
  { name: "Mega Staraptor", baseSlug: "staraptor" },
  { name: "Mega Swampert", baseSlug: "swampert" },
];