// Pokemon Champions Regulation M-B legal pool.
// `slug` is the PokéAPI identifier used to fetch sprites/types.
// `mega` (optional) marks the species as mega-capable. Sprites still render
// from the base form per the "show base forms" UI rule.

export type FormVariant = { name: string; slug: string };
export type MegaInfo = { name: string; slug: string };

export type PokemonSpecies = {
  name: string;
  slug: string;
  forms?: FormVariant[];
  mega?: MegaInfo;
};

export const REG_MB_POOL: PokemonSpecies[] = [
  { name: "Abomasnow", slug: "abomasnow", mega: { name: "Mega Abomasnow", slug: "abomasnow-mega" } },
  { name: "Absol", slug: "absol", mega: { name: "Mega Absol", slug: "absol-mega" } },
  { name: "Aegislash", slug: "aegislash-shield" },
  { name: "Aerodactyl", slug: "aerodactyl", mega: { name: "Mega Aerodactyl", slug: "aerodactyl-mega" } },
  { name: "Aggron", slug: "aggron", mega: { name: "Mega Aggron", slug: "aggron-mega" } },
  { name: "Alakazam", slug: "alakazam", mega: { name: "Mega Alakazam", slug: "alakazam-mega" } },
  { name: "Alcremie", slug: "alcremie" },
  { name: "Altaria", slug: "altaria", mega: { name: "Mega Altaria", slug: "altaria-mega" } },
  { name: "Ampharos", slug: "ampharos", mega: { name: "Mega Ampharos", slug: "ampharos-mega" } },
  { name: "Annihilape", slug: "annihilape" },
  { name: "Appletun", slug: "appletun" },
  { name: "Araquanid", slug: "araquanid" },
  { name: "Arbok", slug: "arbok" },
  {
    name: "Arcanine",
    slug: "arcanine",
    forms: [
      { name: "Arcanine", slug: "arcanine" },
      { name: "Arcanine (Hisui)", slug: "arcanine-hisui" },
    ],
  },
  { name: "Archaludon", slug: "archaludon" },
  { name: "Ariados", slug: "ariados" },
  { name: "Armarouge", slug: "armarouge" },
  { name: "Aromatisse", slug: "aromatisse" },
  { name: "Audino", slug: "audino", mega: { name: "Mega Audino", slug: "audino-mega" } },
  { name: "Aurorus", slug: "aurorus" },
  {
    name: "Avalugg",
    slug: "avalugg",
    forms: [
      { name: "Avalugg", slug: "avalugg" },
      { name: "Avalugg (Hisui)", slug: "avalugg-hisui" },
    ],
  },
  { name: "Azumarill", slug: "azumarill" },
  { name: "Banette", slug: "banette", mega: { name: "Mega Banette", slug: "banette-mega" } },
  { name: "Barbaracle", slug: "barbaracle", mega: { name: "Mega Barbaracle", slug: "barbaracle-mega" } },
  {
    name: "Basculegion",
    slug: "basculegion-male",
    forms: [
      { name: "Basculegion (Male)", slug: "basculegion-male" },
      { name: "Basculegion (Female)", slug: "basculegion-female" },
    ],
  },
  { name: "Bastiodon", slug: "bastiodon" },
  { name: "Beartic", slug: "beartic" },
  { name: "Beedrill", slug: "beedrill", mega: { name: "Mega Beedrill", slug: "beedrill-mega" } },
  { name: "Bellibolt", slug: "bellibolt" },
  { name: "Blastoise", slug: "blastoise", mega: { name: "Mega Blastoise", slug: "blastoise-mega" } },
  { name: "Blaziken", slug: "blaziken", mega: { name: "Mega Blaziken", slug: "blaziken-mega" } },
  { name: "Camerupt", slug: "camerupt", mega: { name: "Mega Camerupt", slug: "camerupt-mega" } },
  { name: "Castform", slug: "castform" },
  { name: "Ceruledge", slug: "ceruledge" },
  { name: "Chandelure", slug: "chandelure", mega: { name: "Mega Chandelure", slug: "chandelure-mega" } },
  { name: "Charizard", slug: "charizard", mega: { name: "Mega Charizard", slug: "charizard-mega-y" } },
  { name: "Chesnaught", slug: "chesnaught", mega: { name: "Mega Chesnaught", slug: "chesnaught-mega" } },
  { name: "Chimecho", slug: "chimecho", mega: { name: "Mega Chimecho", slug: "chimecho-mega" } },
  { name: "Clawitzer", slug: "clawitzer" },
  { name: "Clefable", slug: "clefable", mega: { name: "Mega Clefable", slug: "clefable-mega" } },
  { name: "Cofagrigus", slug: "cofagrigus" },
  { name: "Conkeldurr", slug: "conkeldurr" },
  { name: "Corviknight", slug: "corviknight" },
  { name: "Crabominable", slug: "crabominable", mega: { name: "Mega Crabominable", slug: "crabominable-mega" } },
  {
    name: "Decidueye",
    slug: "decidueye",
    forms: [
      { name: "Decidueye", slug: "decidueye" },
      { name: "Decidueye (Hisui)", slug: "decidueye-hisui" },
    ],
  },
  { name: "Dedenne", slug: "dedenne" },
  { name: "Delphox", slug: "delphox", mega: { name: "Mega Delphox", slug: "delphox-mega" } },
  { name: "Diggersby", slug: "diggersby" },
  { name: "Ditto", slug: "ditto" },
  { name: "Dragalge", slug: "dragalge", mega: { name: "Mega Dragalge", slug: "dragalge-mega" } },
  { name: "Dragapult", slug: "dragapult" },
  { name: "Dragonite", slug: "dragonite", mega: { name: "Mega Dragonite", slug: "dragonite-mega" } },
  { name: "Drampa", slug: "drampa", mega: { name: "Mega Drampa", slug: "drampa-mega" } },
  { name: "Eelektross", slug: "eelektross", mega: { name: "Mega Eelektross", slug: "eelektross-mega" } },
  { name: "Emboar", slug: "emboar", mega: { name: "Mega Emboar", slug: "emboar-mega" } },
  { name: "Emolga", slug: "emolga" },
  { name: "Empoleon", slug: "empoleon" },
  { name: "Espathra", slug: "espathra" },
  { name: "Espeon", slug: "espeon" },
  { name: "Excadrill", slug: "excadrill", mega: { name: "Mega Excadrill", slug: "excadrill-mega" } },
  { name: "Falinks", slug: "falinks", mega: { name: "Mega Falinks", slug: "falinks-mega" } },
  { name: "Farigiraf", slug: "farigiraf" },
  { name: "Feraligatr", slug: "feraligatr", mega: { name: "Mega Feraligatr", slug: "feraligatr-mega" } },
  { name: "Flapple", slug: "flapple" },
  { name: "Flareon", slug: "flareon" },
  {
    name: "Floette",
    slug: "floette",
    forms: [
      { name: "Floette", slug: "floette" },
      { name: "Floette (Eternal)", slug: "floette-eternal" },
    ],
    mega: { name: "Mega Floette", slug: "floette-mega" },
  },
  { name: "Florges", slug: "florges" },
  { name: "Forretress", slug: "forretress" },
  { name: "Froslass", slug: "froslass", mega: { name: "Mega Froslass", slug: "froslass-mega" } },
  { name: "Furfrou", slug: "furfrou" },
  { name: "Gallade", slug: "gallade", mega: { name: "Mega Gallade", slug: "gallade-mega" } },
  { name: "Garbodor", slug: "garbodor" },
  { name: "Garchomp", slug: "garchomp", mega: { name: "Mega Garchomp", slug: "garchomp-mega" } },
  { name: "Gardevoir", slug: "gardevoir", mega: { name: "Mega Gardevoir", slug: "gardevoir-mega" } },
  { name: "Garganacl", slug: "garganacl" },
  { name: "Gengar", slug: "gengar", mega: { name: "Mega Gengar", slug: "gengar-mega" } },
  { name: "Gholdengo", slug: "gholdengo" },
  { name: "Glaceon", slug: "glaceon" },
  { name: "Glalie", slug: "glalie", mega: { name: "Mega Glalie", slug: "glalie-mega" } },
  { name: "Glimmora", slug: "glimmora", mega: { name: "Mega Glimmora", slug: "glimmora-mega" } },
  { name: "Gliscor", slug: "gliscor" },
  { name: "Golurk", slug: "golurk", mega: { name: "Mega Golurk", slug: "golurk-mega" } },
  { name: "Goodra", slug: "goodra" },
  { name: "Gourgeist", slug: "gourgeist-average" },
  { name: "Greninja", slug: "greninja", mega: { name: "Mega Greninja", slug: "greninja-mega" } },
  { name: "Grimmsnarl", slug: "grimmsnarl" },
  { name: "Gyarados", slug: "gyarados", mega: { name: "Mega Gyarados", slug: "gyarados-mega" } },
  { name: "Hatterene", slug: "hatterene" },
  { name: "Hawlucha", slug: "hawlucha", mega: { name: "Mega Hawlucha", slug: "hawlucha-mega" } },
  { name: "Heliolisk", slug: "heliolisk" },
  { name: "Heracross", slug: "heracross", mega: { name: "Mega Heracross", slug: "heracross-mega" } },
  { name: "Hippowdon", slug: "hippowdon" },
  { name: "Houndoom", slug: "houndoom", mega: { name: "Mega Houndoom", slug: "houndoom-mega" } },
  { name: "Houndstone", slug: "houndstone" },
  { name: "Hydrapple", slug: "hydrapple" },
  { name: "Hydreigon", slug: "hydreigon" },
  { name: "Incineroar", slug: "incineroar" },
  { name: "Infernape", slug: "infernape" },
  { name: "Jolteon", slug: "jolteon" },
  { name: "Kangaskhan", slug: "kangaskhan", mega: { name: "Mega Kangaskhan", slug: "kangaskhan-mega" } },
  { name: "Kingambit", slug: "kingambit" },
  { name: "Kleavor", slug: "kleavor" },
  { name: "Klefki", slug: "klefki" },
  { name: "Kommo-o", slug: "kommo-o" },
  { name: "Krookodile", slug: "krookodile" },
  { name: "Leafeon", slug: "leafeon" },
  { name: "Liepard", slug: "liepard" },
  { name: "Lopunny", slug: "lopunny", mega: { name: "Mega Lopunny", slug: "lopunny-mega" } },
  { name: "Lucario", slug: "lucario", mega: { name: "Mega Lucario", slug: "lucario-mega" } },
  { name: "Luxray", slug: "luxray" },
  {
    name: "Lycanroc",
    slug: "lycanroc-midday",
    forms: [
      { name: "Lycanroc (Midday)", slug: "lycanroc-midday" },
      { name: "Lycanroc (Midnight)", slug: "lycanroc-midnight" },
      { name: "Lycanroc (Dusk)", slug: "lycanroc-dusk" },
    ],
  },
  { name: "Machamp", slug: "machamp" },
  { name: "Malamar", slug: "malamar", mega: { name: "Mega Malamar", slug: "malamar-mega" } },
  { name: "Mamoswine", slug: "mamoswine" },
  { name: "Manectric", slug: "manectric", mega: { name: "Mega Manectric", slug: "manectric-mega" } },
  { name: "Maushold", slug: "maushold-family-of-four" },
  { name: "Mawile", slug: "mawile", mega: { name: "Mega Mawile", slug: "mawile-mega" } },
  { name: "Medicham", slug: "medicham", mega: { name: "Mega Medicham", slug: "medicham-mega" } },
  { name: "Meganium", slug: "meganium", mega: { name: "Mega Meganium", slug: "meganium-mega" } },
  { name: "Meowscarada", slug: "meowscarada" },
  {
    name: "Meowstic",
    slug: "meowstic-male",
    forms: [
      { name: "Meowstic (Male)", slug: "meowstic-male" },
      { name: "Meowstic (Female)", slug: "meowstic-female" },
    ],
    mega: { name: "Mega Meowstic", slug: "meowstic-male-mega" },
  },
  { name: "Metagross", slug: "metagross", mega: { name: "Mega Metagross", slug: "metagross-mega" } },
  { name: "Milotic", slug: "milotic" },
  { name: "Mimikyu", slug: "mimikyu-disguised" },
  { name: "Morpeko", slug: "morpeko-full-belly" },
  { name: "Mr. Rime", slug: "mr-rime" },
  { name: "Mudsdale", slug: "mudsdale" },
  { name: "Musharna", slug: "musharna" },
  {
    name: "Ninetales",
    slug: "ninetales",
    forms: [
      { name: "Ninetales (Kantonian)", slug: "ninetales" },
      { name: "Ninetales (Alolan)", slug: "ninetales-alola" },
    ],
  },
  { name: "Noivern", slug: "noivern" },
  { name: "Oranguru", slug: "oranguru" },
  { name: "Orthworm", slug: "orthworm" },
  { name: "Overqwil", slug: "overqwil" },
  { name: "Palafin", slug: "palafin-zero" },
  { name: "Pangoro", slug: "pangoro" },
  { name: "Passimian", slug: "passimian" },
  { name: "Watchog", slug: "watchog" },
  { name: "Pelipper", slug: "pelipper" },
  { name: "Pidgeot", slug: "pidgeot", mega: { name: "Mega Pidgeot", slug: "pidgeot-mega" } },
  { name: "Pikachu", slug: "pikachu" },
  { name: "Pinsir", slug: "pinsir", mega: { name: "Mega Pinsir", slug: "pinsir-mega" } },
  { name: "Politoed", slug: "politoed" },
  { name: "Polteageist", slug: "polteageist" },
  { name: "Primarina", slug: "primarina" },
  { name: "Pyroar", slug: "pyroar-male", mega: { name: "Mega Pyroar", slug: "pyroar-mega" } },
  { name: "Quaquaval", slug: "quaquaval" },
  { name: "Qwilfish", slug: "qwilfish" },
  {
    name: "Raichu",
    slug: "raichu",
    forms: [
      { name: "Raichu", slug: "raichu" },
      { name: "Raichu (Alolan)", slug: "raichu-alola" },
    ],
    mega: { name: "Mega Raichu", slug: "raichu-mega-x" },
  },
  { name: "Rampardos", slug: "rampardos" },
  { name: "Reuniclus", slug: "reuniclus" },
  { name: "Rhyperior", slug: "rhyperior" },
  { name: "Roserade", slug: "roserade" },
  {
    name: "Rotom",
    slug: "rotom",
    forms: [
      { name: "Rotom", slug: "rotom" },
      { name: "Rotom (Heat)", slug: "rotom-heat" },
      { name: "Rotom (Wash)", slug: "rotom-wash" },
      { name: "Rotom (Frost)", slug: "rotom-frost" },
      { name: "Rotom (Fan)", slug: "rotom-fan" },
      { name: "Rotom (Mow)", slug: "rotom-mow" },
    ],
  },
  { name: "Runerigus", slug: "runerigus" },
  { name: "Sableye", slug: "sableye", mega: { name: "Mega Sableye", slug: "sableye-mega" } },
  { name: "Salazzle", slug: "salazzle" },
  {
    name: "Samurott",
    slug: "samurott",
    forms: [
      { name: "Samurott", slug: "samurott" },
      { name: "Samurott (Hisui)", slug: "samurott-hisui" },
    ],
  },
  { name: "Sandaconda", slug: "sandaconda" },
  { name: "Sceptile", slug: "sceptile", mega: { name: "Mega Sceptile", slug: "sceptile-mega" } },
  { name: "Scizor", slug: "scizor", mega: { name: "Mega Scizor", slug: "scizor-mega" } },
  { name: "Scolipede", slug: "scolipede", mega: { name: "Mega Scolipede", slug: "scolipede-mega" } },
  { name: "Scovillain", slug: "scovillain", mega: { name: "Mega Scovillain", slug: "scovillain-mega" } },
  { name: "Scrafty", slug: "scrafty", mega: { name: "Mega Scrafty", slug: "scrafty-mega" } },
  { name: "Serperior", slug: "serperior" },
  { name: "Sharpedo", slug: "sharpedo", mega: { name: "Mega Sharpedo", slug: "sharpedo-mega" } },
  { name: "Simipour", slug: "simipour" },
  { name: "Simisage", slug: "simisage" },
  { name: "Simisear", slug: "simisear" },
  { name: "Sinistcha", slug: "sinistcha" },
  { name: "Skarmory", slug: "skarmory", mega: { name: "Mega Skarmory", slug: "skarmory-mega" } },
  { name: "Skeledirge", slug: "skeledirge" },
  {
    name: "Slowbro",
    slug: "slowbro",
    forms: [
      { name: "Slowbro", slug: "slowbro" },
      { name: "Slowbro (Galar)", slug: "slowbro-galar" },
    ],
    mega: { name: "Mega Slowbro", slug: "slowbro-mega" },
  },
  {
    name: "Slowking",
    slug: "slowking",
    forms: [
      { name: "Slowking", slug: "slowking" },
      { name: "Slowking (Galar)", slug: "slowking-galar" },
    ],
  },
  { name: "Slurpuff", slug: "slurpuff" },
  { name: "Sneasler", slug: "sneasler" },
  { name: "Snorlax", slug: "snorlax" },
  { name: "Spiritomb", slug: "spiritomb" },
  { name: "Staraptor", slug: "staraptor", mega: { name: "Mega Staraptor", slug: "staraptor-mega" } },
  { name: "Starmie", slug: "starmie", mega: { name: "Mega Starmie", slug: "starmie-mega" } },
  { name: "Steelix", slug: "steelix", mega: { name: "Mega Steelix", slug: "steelix-mega" } },
  { name: "Stunfisk", slug: "stunfisk" },
  { name: "Swampert", slug: "swampert", mega: { name: "Mega Swampert", slug: "swampert-mega" } },
  { name: "Sylveon", slug: "sylveon" },
  { name: "Talonflame", slug: "talonflame" },
  {
    name: "Tauros",
    slug: "tauros",
    forms: [
      { name: "Tauros", slug: "tauros" },
      { name: "Tauros (Combat Paldean)", slug: "tauros-paldea-combat-breed" },
      { name: "Tauros (Blaze Paldean)", slug: "tauros-paldea-blaze-breed" },
      { name: "Tauros (Aqua Paldean)", slug: "tauros-paldea-aqua-breed" },
    ],
  },
  { name: "Tinkaton", slug: "tinkaton" },
  { name: "Torkoal", slug: "torkoal" },
  { name: "Torterra", slug: "torterra" },
  { name: "Toucannon", slug: "toucannon" },
  { name: "Toxapex", slug: "toxapex" },
  { name: "Toxicroak", slug: "toxicroak" },
  { name: "Trevenant", slug: "trevenant" },
  { name: "Tsareena", slug: "tsareena" },
  {
    name: "Typhlosion",
    slug: "typhlosion",
    forms: [
      { name: "Typhlosion", slug: "typhlosion" },
      { name: "Typhlosion (Hisui)", slug: "typhlosion-hisui" },
    ],
  },
  { name: "Tyranitar", slug: "tyranitar", mega: { name: "Mega Tyranitar", slug: "tyranitar-mega" } },
  { name: "Tyrantrum", slug: "tyrantrum" },
  { name: "Umbreon", slug: "umbreon" },
  { name: "Vanilluxe", slug: "vanilluxe" },
  { name: "Vaporeon", slug: "vaporeon" },
  { name: "Venusaur", slug: "venusaur", mega: { name: "Mega Venusaur", slug: "venusaur-mega" } },
  { name: "Victreebel", slug: "victreebel", mega: { name: "Mega Victreebel", slug: "victreebel-mega" } },
  { name: "Vileplume", slug: "vileplume" },
  { name: "Vivillon", slug: "vivillon" },
  { name: "Volcarona", slug: "volcarona" },
  { name: "Weavile", slug: "weavile" },
  { name: "Whimsicott", slug: "whimsicott" },
  { name: "Wyrdeer", slug: "wyrdeer" },
  {
    name: "Zoroark",
    slug: "zoroark",
    forms: [
      { name: "Zoroark", slug: "zoroark" },
      { name: "Zoroark (Hisui)", slug: "zoroark-hisui" },
    ],
  },
];
