import { createFileRoute, Link } from "@tanstack/react-router";

export const Route = createFileRoute("/legal")({
  head: () => ({
    meta: [
      { title: "Legal & Disclaimers — Pokémon Champions Draft" },
      {
        name: "description",
        content:
          "Fan-project disclaimers, trademark acknowledgements, and PokéAPI attribution for the Pokémon Champions Draft randomizer.",
      },
      { property: "og:title", content: "Legal & Disclaimers — Pokémon Champions Draft" },
      {
        property: "og:description",
        content: "Unofficial fan project. Trademark and attribution notices.",
      },
      { property: "og:type", content: "article" },
      {
        property: "og:url",
        content: "https://poke-champions-draft.lovable.app/legal",
      },
      { name: "twitter:title", content: "Legal & Disclaimers — Pokémon Champions Draft" },
      {
        name: "twitter:description",
        content: "Unofficial fan project. Trademark and attribution notices.",
      },
    ],
    links: [
      {
        rel: "canonical",
        href: "https://poke-champions-draft.lovable.app/legal",
      },
    ],
  }),
  component: LegalPage,
});

function LegalPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <header className="border-b border-border bg-card/40 backdrop-blur">
        <div className="mx-auto flex max-w-3xl items-center justify-between px-6 py-5">
          <Link to="/" className="text-sm font-semibold text-muted-foreground hover:text-accent">
            ← Back to draft
          </Link>
          <span className="text-xs text-muted-foreground">Legal</span>
        </div>
      </header>
      <main className="mx-auto max-w-3xl px-6 py-10">
        <h1 className="text-3xl font-black tracking-tight">Legal & Disclaimers</h1>
        <p className="mt-2 text-sm text-muted-foreground">
          Last updated: June 2026
        </p>

        <section className="mt-8 space-y-3">
          <h2 className="text-xl font-bold">Unofficial fan project</h2>
          <p className="text-sm leading-relaxed text-muted-foreground">
            Pokémon Champions Draft is a non-commercial fan-made tool. It is{" "}
            <strong className="text-foreground">not affiliated with, endorsed,
            sponsored, or approved by</strong> Nintendo, Game Freak, Creatures
            Inc., or The Pokémon Company. No revenue is generated by this site.
          </p>
        </section>

        <section className="mt-8 space-y-3">
          <h2 className="text-xl font-bold">Trademarks & copyrights</h2>
          <p className="text-sm leading-relaxed text-muted-foreground">
            Pokémon, Pokémon character names, and all related images, sounds,
            and trademarks are the property of their respective owners —
            including Nintendo, Game Freak, Creatures Inc., and The Pokémon
            Company. Their use here is for descriptive and informational
            purposes only to identify the species a player has drafted.
          </p>
        </section>

        <section className="mt-8 space-y-3">
          <h2 className="text-xl font-bold">Data & sprite attribution</h2>
          <p className="text-sm leading-relaxed text-muted-foreground">
            Pokémon names, stats, types, abilites, moves and sprite artwork are fetched from{" "}
            <a
              href="https://pokeapi.co"
              target="_blank"
              rel="noreferrer"
              className="text-accent underline"
            >
              PokéAPI
            </a>{" "}
            and cached locally in your browser per PokéAPI's fair-use
            guidelines. Sprite imagery served by PokéAPI originates from the
            Pokémon games and is owned by the rights holders listed above.
          </p>
        </section>

        <section className="mt-8 space-y-3">
          <h2 className="text-xl font-bold">No warranty</h2>
          <p className="text-sm leading-relaxed text-muted-foreground">
            This site is provided "as is" without warranty of any kind. The
            regulation pool, mega list, and form mappings are maintained
            manually and may lag behind official rules updates.
          </p>
        </section>

        <section className="mt-8 space-y-3">
          <h2 className="text-xl font-bold">Audio</h2>
          <p className="text-sm leading-relaxed text-muted-foreground">
            The shiny chime is an original synthesized sparkle sound. It is
            not from any Pokémon game.
          </p>
        </section>

        <div className="mt-12 border-t border-border pt-6">
          <Link to="/" className="text-sm font-semibold text-accent hover:underline">
            ← Back to draft
          </Link>
        </div>
      </main>
    </div>
  );
}
